#spring.data.mongodb.ssl.enabled=true
#spring.data.mongodb.ssl.trust-store=C:/Users/aman.goel1/docdb-truststore.jks
#spring.data.mongodb.ssl.trust-store-password=changeit

#spring.data.mongodb.uri=mongodb://aglpu:>3HrYppm>RO[19ddWbR[5XLp3Mp-@localhost:27017/?tls=true&tlsCAFile=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
#spring.data.mongodb.uri=mongodb://aglpu:PjNIcllwcG0+Uk9bMTlkZFdiUls1WExwM01wLQ==@localhost:27017/?tls=true&tlsAllowInvalidHostnames=true&retryWrites=false
spring.data.mongodb.database=BookStore