name: Build & Deploy to ECS Fargate

on:
  push:
    branches: ["develop"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag & Push Image
        run: |
          SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          BASE="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}"
          TS=$(date +'%Y%m%d-%H%M')
          BUILD=${{ github.run_number }}
          
          docker build -t myapp .
          
          docker tag myapp:latest $BASE:$SHA
          docker tag myapp:latest $BASE:latest
          docker tag myapp:latest $BASE:build-$BUILD

          echo "Pushing the following images:"
          echo "$BASE:$SHA"
          echo "$BASE:build-$BUILD"
          echo "$BASE:latest"
          
          docker push $BASE:$SHA
          docker push $BASE:build-$BUILD
          docker push $BASE:latest
          
          #echo "IMAGE_TAG=$SHA" >> $GITHUB_ENV

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster java-mongo-example \
            --service java-mongo-example \
            --force-new-deployment
